[versions]
jetbrains-changelog = "2.5.0"
jetbrains-ide-starter = "243.28141.18"
jetbrains-intellij-platform = "2.10.5"
junit = "6.0.1"
kodein-di = "7.30.0"
kotlin = "2.2.21"
kotlinx-coroutines = "1.4.0"
kotlinx-serialization = "1.9.0"
mockk = "1.14.2"
strikt = "0.35.1"

[libraries]
jetbrains-driver = { group = "com.jetbrains.intellij.driver", name = "driver-sdk", version.ref = "jetbrains-ide-starter" }
jetbrains-ide-starter = { group = "com.jetbrains.intellij.tools", name = "ide-starter-squashed", version.ref = "jetbrains-ide-starter" }
jetbrains-ide-starter-driver = { group = "com.jetbrains.intellij.tools", name = "ide-starter-driver", version.ref = "jetbrains-ide-starter" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
kodein-di = { group = "org.kodein.di", name = "kodein-di-jvm", version.ref = "kodein-di" }
kotlinx-coroutines-core-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
strikt-core = { group = "io.strikt", name = "strikt-core", version.ref = "strikt" }

[plugins]
jetbrains-changelog = { id = "org.jetbrains.changelog", version.ref = "jetbrains-changelog" }
jetbrains-intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "jetbrains-intellij-platform" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
